# Generated by Django 3.0.3 on 2020-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tweet_hash_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
