# Generated by Django 3.0.3 on 2020-02-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hashtag_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
