# Generated by Django 3.0.3 on 2020-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200214_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
